#================== BEACON NETHER ROOF CONFIG ==================#
#Damage dealt to players on nether roof that are not near a beacon
damage: 4
#Minimum distance a player has to be from a beacon to stop taking damage
distance: 50
#Nether roof damage delay in seconds
delay: 2